name: kwando
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
    - panel>=1.7.4
    - bokeh>=3.7.3
    - pandas>=2.0.0
    - numpy>=2.3.1
    - scipy>=1.16.0
    - tabulate>=0.9.0
    - jupyter>=1.1.1
